dev:
  accountid: 730335449261
  region:
  statefileBucket: dev-statefile
  dynamodblock: dev-dynamodb
test:
  accountid: 56789999999999
  region:
  statefileBucket: test-statefile
  dynamodblock: test-dynamodb
prod:
  accountid: 143678902
  region: 
  statefileBucket: prod-statefile
  dynamodblock: prod-statefile
